version: '3.8'

services:
  kafka:
    container_name: kafka
    image: quay.io/ccxdev/kafka-no-zk:latest
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=calculator-requests:1:1,calculator-responses:1:1
